import { ethers } from 'ethers';

// ABI SakuRegistry (sesuai yang kamu kirim)
export const SAKU_ABI = [{"inputs":[{"internalType":"address","name":"_idrxAddress","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"phoneHash","type":"bytes32"},{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Registered","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"receiverHash","type":"bytes32"},{"indexed":false,"internalType":"address","name":"sender","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Transferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"phoneHash","type":"bytes32"},{"indexed":false,"internalType":"address","name":"oldAccount","type":"address"},{"indexed":false,"internalType":"address","name":"newAccount","type":"address"}],"name":"UpdatedRegistration","type":"event"},{"inputs":[{"internalType":"bytes32","name":"phoneHash","type":"bytes32"}],"name":"getAccount","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"idrxToken","outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"phoneHash","type":"bytes32"}],"name":"isRegistered","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"phoneHash","type":"bytes32"}],"name":"login","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"name":"phoneToAccount","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"phoneHash","type":"bytes32"}],"name":"register","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"receiverHash","type":"bytes32"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"transferIDRX","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"phoneHash","type":"bytes32"},{"internalType":"address","name":"newAccount","type":"address"}],"name":"updateRegistration","outputs":[],"stateMutability":"nonpayable","type":"function"}];

export const hashPhone = (phone: string) => {
  return ethers.keccak256(ethers.toUtf8Bytes(phone));
};

export const getProvider = () => new ethers.JsonRpcProvider(process.env.RPC_URL);